### ISSUE TITLE
Sacar o reemplazar la opción de invitar contactos desde Google

### ISSUE THREAD

**Issue by lobit0** [piratas-ar/loomio#15]
Dice: "¿No recuerdas un correo electrónico? Importa tus contactos desde Google"

Si hay algo ya inventado que permita fácilmente hacer realidad un "Importa tus contactos desde Thunderbird o tu correo pirata", genial.

Sino lo sacamos y ya.

**Comment by fauno** [comment]
+1 además es pésima esa feature le pide a las piratas que pongan su contraseña de google e inviten a cualquier cantidad de gente que nada que ver

**Comment by fauno** [comment]
se puede subir un csv o ldif que es lo que exporta thunderbird (igual siempre me parecieron cualquiera estas features...)

**Comment by fauno** [comment]
lo acabo de cerrar en 7049afa1fb6b6253d1b5e7037a76580b444ef55d
