### ISSUE TITLE
Agregar links

### ISSUE THREAD

**Issue by fauno** [piratas-ar/loomio#19]
- [ ] wiki
- [ ] irc
- [ ] listas

como con los pads se pueden generar links directo a los articulos para la wiki no?

**Comment by lobit0** [comment]
no entendí, cómo sería?

**Comment by fauno** [comment]
dejame hacer memoria, puede ser:
- poner los links a las cosas mas usadas en la barra de navegacion
- crear vinculos automaticos a distintos recursos, para que de una discusion puedas pasar a su canal irc, pad, lista y articulo wiki

**Comment by lobit0** [comment]
ah si, está bueno

ahi edito y me pongo a favor en el loomio :P

(off-topic: flasheo que vamos a terminar sacando un fork del tor browser bundle para participar de las actividades del partido :P o una distro)
