### ISSUE TITLE
Botón Ayuda

### ISSUE THREAD

**Issue by pabloneira** [piratas-ar/loomio#50]
Colocar Botón ayuda (si se puede antes de registrarse), este botón le da la posibilidad a la plataforma de crecer hasta 6.000.000.000 de usuarios en todo el planeta.

**Comment by seykron** [comment]
¿Qué haría el botón de ayuda? Ya hay un ticket levantado para mostrar mejor la información de la homepage para personas que se acercan por primera vez:

https://github.com/piratas-ar/loomio/issues/41

**Comment by pabloneira** [comment]
El botón es un Link a una página que ofrece varias alternativas para comunicarse y solicitar ayuda ejemplo Grupo ayuda de telegram, sala de ayuda jabber, Irc pirata y como se configura, un email de las cuentas piratas que comparten la contraseña varios piratas sombra, un número whatsapp que te agrega a un grupo whatsapp de ayuda consenso pirata, un mail que te ayuda a registrarte para recibir los correos de la lista pirata etc. Estos grupos de ayuda estarían formados por piratas sombra o media sombra, lo importante es que hacés click y alguien te responde no te dejan esperando, después el tiempo que tarde en ingresar y usarlo como esta previsto depende de cada persona.

**Comment by pabloneira** [comment]
Ejemplo práctico para el botón ayuda.
La fábrica de termotanques gobal está a punto de pedir la quiebra. Un grupo de 3 trabajadores de la misma deciden que cada uno va a realizar la acción que considere mas conveniente y luego van a compartir sus experiencias. Juan busca un abogado para negociar con los empleadores. Pedro habla con el delegado. Miguel deside usar consenso pirata para buscar una solución a su vida, el sabe fabricar termotanques, sabe como modificarlos para que duren toda la vida, en su lugar de residencia no toman trabajadores, sueña con emprender una fábrica llamada termotanques sapucai y considera que usando la plataforma pueden participar en la misma los empleadores, nuevos inversores, otros desocupados, algunos de sus actuales compañeros de trabajo etc. El sabe algo de informática sus compañeros no, inicia su proyecto con el botón ayuda. (este texto es simplemente un borrador, falta terminar, esta incompleto)

**Comment by m4tu5** [comment]
Muchachas, cambien el título del issue a algo que lo describa, ahora mismo el título es "Pablo", un poco personalista, no?

**Comment by fauno** [comment]
el nuevo menú resuelve esto?

**Comment by pabloneira** [comment]
[19:40] qwebirc v0.90
[19:40] Copyright (C) 2008-2010 Chris Porter and the qwebirc project.
[19:40] http://www.qwebirc.org

## [19:40] Licensed under the GNU General Public License, Version 2.

[19:40] == **\* (qwebirc) Looking up your hostname...
[19:40] == **\* (qwebirc) Couldn't look up your hostname!
[19:40] == Connected to server.
[19:40] -london-uk.pirateirc.net- **\* Looking up your hostname...
[19:40] -london-uk.pirateirc.net- **\* Checking Ident
[19:40] -london-uk.pirateirc.net- **\* Found your hostname
[19:40] -london-uk.pirateirc.net- **\* Got Ident response
[19:40] == CGI:IRC host/IP set to 179.38.255.42 179.38.255.42
[19:40] == Attempting SASL authentication...
[19:40] == Disconnected from server: Connection to IRC server lost.

2015-08-30 13:25 GMT-03:00 fauno notifications@github.com:

**Comment by pabloneira** [comment]
No pude entrar al chat

**Comment by pabloneira** [comment]
Ahora si pude entrar me atendió minitrue y le explique que estaba probando el chat. Mi opinión es que el chat no es para una persona que ingresa con pocos conocimientos.

**Comment by sudoaza** [comment]
cierro este, estaria incluido en este otro https://github.com/piratas-ar/loomio/issues/41
