### ISSUE TITLE
Link al pad en "nuevo loomio"

### ISSUE THREAD

**Issue by martinszy** [piratas-ar/loomio#54]
En el nuevo loomio, que se promociona desde el encabezado del sitio, no hay enlaces a los pads de cada discusión.
Esto si está la versión vieja, estaría bueno que esté en ambas versiones si es que se va a seguir promocionando la nueva.

**Comment by fauno** [comment]
la nueva es de prueba todavía...

si alguien sabe angular adelante, no tengo ganas de aprender ahora :P

## 

http://librevpn.org.ar

**Comment by martinszy** [comment]
Aunque me gusta más la nueva, la sacaría si no soporta todas las
funcionalidades necesarias.
Si alguien se copa en esta semana se puede, sino ocultaría el enlace.

**Comment by martinszy** [comment]
Sigue siendo importante, miren este comentario:
https://consenso.partidopirata.com.ar/d/B2zTxUKW/repudiar-el-ataque-a-miembros-de-la-comunidad-lgtb-de-mar-del-plata#comment-1053

**Comment by fauno** [comment]
no puede hacerlo otrx? ♬

## 

http://partidopirata.com.ar

**Comment by fauno** [comment]
lo estuve viendo y como no se puede llamar a `ENV['COLLABORATIVE_TEXT_URL']` dentro del template de angular `lineman/app/components/thread_page/thread_page.haml` me falla la compilación.  no sabria como obtener ese valor...

**Comment by fauno** [comment]
bueh hasta que sepa como hacer esto o alguien más lo haga queda hardcodeada la url de los pads :P

**Comment by sudoaza** [comment]
Esto ya esta, cierro
