### ISSUE TITLE
vincular pads

### ISSUE THREAD

**Issue by fauno** [piratas-ar/loomio#6]
un boton que vincule pads de trabajo

**Comment by to-more** [comment]
ademàs se puede mostrar el texto de las propuestas q tienen avance

**Comment by fauno** [comment]
ya traer el texto de un pad es otro quilombo :P

**Comment by to-more** [comment]
sep pero no es tan complejo se puede hacer.
hay una gema[1](https://github.com/jhollinger/ruby-etherpad-lite) que use para eso, es bastante simple.

**Comment by sudoaza** [comment]
+1 a traer el texto del pad y mostrarlo abajo del mensaje original.

**Comment by fauno** [comment]
y cada cuanto se actualizaría? (nunca me llegó la notificación de estos comentarios!)

**Comment by sudoaza** [comment]
ponle actualizarlo cada 5 minutos, esconder los // Comentarios y parsear el md.

**Comment by fauno** [comment]
y solo traer las revisiones guardadas? cada cinco minutos me parece mucho para pads que quedan inactivos muy rapido... que te parece cada vez que se carga la página?

**Comment by m4tu5** [comment]
y un mix de ambas, para tambien tener cuebierto el escenarios en el que somos millones de piratas accediendo a todo el contenido todo el tiempo?

actualiza al cargar la página, siempre que hayan pasado al menos 5 minutos desde su ultima actualización

**Comment by fauno** [comment]
+1 @m4tu5

**Comment by to-more** [comment]
On 08/06/15 13:18, fauno wrote:

> +1 @m4tu5 https://github.com/m4tu5
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/piratas-ar/loomio/issues/6#issuecomment-110060711.
> 
> +1

entonces traemos el texto...

**Comment by sudoaza** [comment]
Si guardamos cuando fue el ultimo update podemos updatearlo cada x minutos, donde x es la cantidad de minutos que hace se modifico o el minimo de 5min. Entonces empieza 5min, 10min, 20min, 40min, 1h20min, 2h40m y asi hasta que se actualiza y vuelve a 0. Tambien podria tener un maximo de 24h ponele, pero talvez la este galponeando :P

**Comment by fauno** [comment]
no entiendo por qué van aumentando los tiempos geométricamente y en un momento se resetean

**Comment by sudoaza** [comment]
se resetean cuando se actualiza, si se actualiza seguido se espera poco, si no se actualiza cada vez se reisa menos hasta un maximo

**Comment by m4tu5** [comment]
entiendo que para implementar esto tenés que comparar el pad que levantás con el que tenés.
una línea más de código (al menos) a cambio de chequeos menos frecuentes ... donde está el balance?

**Comment by fauno** [comment]
que cuando haya cambios en el pad figure como un evento en la tira de comentarios, como se ven las posiciones. algo como "hubo X cambios en el pad (link)"

**Comment by sudoaza** [comment]
mmmm yo trataria de mostrar en loomio el estado actual del pad siempe, aunque lo  del evenot tb puede ser

**Comment by lobit0** [comment]
Yo no sé si metería los pads en la conversación de Loomio.

Me parece complejo de hacer y no sé si aporta tanto. Al menos no le daría tanta prioridad.

¿No hará más pesada la página y la volverá menos accesible para celulares y compus menos potentes?

Yo pondría los enlaces a los pads junto a la sección de referencias.

Pero es mi opinión nomás y los veo re cebados buscando la manera, tampoco la quiero galponear jaja.

Si les copa y ven que lo pueden llevar a cabo, no me opongo. Lo probamos y vemos qué onda. Y si no resulta para el partido, capaz le resulta a algún otro grupo y se aprovecha igual.

**Comment by fauno** [comment]
empecemos con un boton que vincule un pad, que es solo crear un link que use el mismo id que la discusion, y despues vemos como galponear con la api

**Comment by fauno** [comment]
estuvimos hablando en irc de hacerlo en distintas etapas:
- primera etapa: un boton bien visible que linkee a `https://pad.partidopirata.com.ar/p/#{discussion.key}` (hay que ver donde quedaria mejor)
- segunda etapa: traer a traves de la api el texto del pad y guardarlo o mostrarlo como parte del contexto, borrando los comentarios (`/^\/\/ /d`).  esto ayudaria a que de los pads salga un texto final, porque la mayor parte del tiempo quedan colgadisimos.

en loomio.org tambien estan interesadas en esta feature asi que habria que implementarlo en master, no en piratas, asi les podemos mandar el pr.

**Comment by fauno** [comment]
en la casona le pusimos el botoncito de pads vinculados a las discusiones, ya está en producción

**Comment by sudoaza** [comment]
Cierro esto que ya esta, si quieren meterle mas fichurs abran de vuelta o creen otro
