### ISSUE TITLE
eliminar los js de googletagmanager

### ISSUE THREAD

**Issue by m4tu5** [piratas-ar/loomio#7]
ademas de los scripts propios, el sitio esta queriendo ejecutar js de googletagmanager.

siendo que es una herramienta que se usa principalmente para marketing, medir conversiones etc, me parece bueno si podemos buscar la forma de eliminarla.

**Comment by m4tu5** [comment]
hay un llamado al `partial` que renderiza google-tag-manager en el layout de la aplicación.
app/views/layouts/application.html.haml

encontre tambien que hay cosas de google_analytics
app/views/application/_google_analytics.html.haml

aun no se quien lo llama para renderizarlo.

**Comment by fauno** [comment]
m4tu5 notifications@github.com writes:

> hay un llamado al `partial` que renderiza google-tag-manager en el layout de la aplicación.
> app/views/layouts/application.html.haml
> 
> encontre tambien que hay cosas de google_analytics
> app/views/application/_google_analytics.html.haml
> 
> aun no se quien lo llama para renderizarlo.

mandá el parche nomás!

## 

:{
